// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: orbita_kinematics.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Reachy.Sdk.Kinematics {
  public static partial class OrbitaKinematics
  {
    static readonly string __ServiceName = "reachy.sdk.kinematics.OrbitaKinematics";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.OrbitaIKRequest> __Marshaller_reachy_sdk_kinematics_OrbitaIKRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.OrbitaIKRequest.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.OrbitaIKSolution> __Marshaller_reachy_sdk_kinematics_OrbitaIKSolution = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.OrbitaIKSolution.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.LookVector> __Marshaller_reachy_sdk_kinematics_LookVector = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.LookVector.Parser));
    static readonly grpc::Marshaller<global::Reachy.Sdk.Kinematics.Quaternion> __Marshaller_reachy_sdk_kinematics_Quaternion = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Reachy.Sdk.Kinematics.Quaternion.Parser));

    static readonly grpc::Method<global::Reachy.Sdk.Kinematics.OrbitaIKRequest, global::Reachy.Sdk.Kinematics.OrbitaIKSolution> __Method_ComputeOrbitaIK = new grpc::Method<global::Reachy.Sdk.Kinematics.OrbitaIKRequest, global::Reachy.Sdk.Kinematics.OrbitaIKSolution>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ComputeOrbitaIK",
        __Marshaller_reachy_sdk_kinematics_OrbitaIKRequest,
        __Marshaller_reachy_sdk_kinematics_OrbitaIKSolution);

    static readonly grpc::Method<global::Reachy.Sdk.Kinematics.LookVector, global::Reachy.Sdk.Kinematics.Quaternion> __Method_GetQuaternionTransform = new grpc::Method<global::Reachy.Sdk.Kinematics.LookVector, global::Reachy.Sdk.Kinematics.Quaternion>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetQuaternionTransform",
        __Marshaller_reachy_sdk_kinematics_LookVector,
        __Marshaller_reachy_sdk_kinematics_Quaternion);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Reachy.Sdk.Kinematics.OrbitaKinematicsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of OrbitaKinematics</summary>
    [grpc::BindServiceMethod(typeof(OrbitaKinematics), "BindService")]
    public abstract partial class OrbitaKinematicsBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Kinematics.OrbitaIKSolution> ComputeOrbitaIK(global::Reachy.Sdk.Kinematics.OrbitaIKRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Reachy.Sdk.Kinematics.Quaternion> GetQuaternionTransform(global::Reachy.Sdk.Kinematics.LookVector request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for OrbitaKinematics</summary>
    public partial class OrbitaKinematicsClient : grpc::ClientBase<OrbitaKinematicsClient>
    {
      /// <summary>Creates a new client for OrbitaKinematics</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public OrbitaKinematicsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for OrbitaKinematics that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public OrbitaKinematicsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected OrbitaKinematicsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected OrbitaKinematicsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Reachy.Sdk.Kinematics.OrbitaIKSolution ComputeOrbitaIK(global::Reachy.Sdk.Kinematics.OrbitaIKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeOrbitaIK(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Kinematics.OrbitaIKSolution ComputeOrbitaIK(global::Reachy.Sdk.Kinematics.OrbitaIKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ComputeOrbitaIK, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.OrbitaIKSolution> ComputeOrbitaIKAsync(global::Reachy.Sdk.Kinematics.OrbitaIKRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ComputeOrbitaIKAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.OrbitaIKSolution> ComputeOrbitaIKAsync(global::Reachy.Sdk.Kinematics.OrbitaIKRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ComputeOrbitaIK, null, options, request);
      }
      public virtual global::Reachy.Sdk.Kinematics.Quaternion GetQuaternionTransform(global::Reachy.Sdk.Kinematics.LookVector request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuaternionTransform(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Reachy.Sdk.Kinematics.Quaternion GetQuaternionTransform(global::Reachy.Sdk.Kinematics.LookVector request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetQuaternionTransform, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.Quaternion> GetQuaternionTransformAsync(global::Reachy.Sdk.Kinematics.LookVector request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuaternionTransformAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Reachy.Sdk.Kinematics.Quaternion> GetQuaternionTransformAsync(global::Reachy.Sdk.Kinematics.LookVector request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetQuaternionTransform, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override OrbitaKinematicsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new OrbitaKinematicsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(OrbitaKinematicsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ComputeOrbitaIK, serviceImpl.ComputeOrbitaIK)
          .AddMethod(__Method_GetQuaternionTransform, serviceImpl.GetQuaternionTransform).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, OrbitaKinematicsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ComputeOrbitaIK, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Kinematics.OrbitaIKRequest, global::Reachy.Sdk.Kinematics.OrbitaIKSolution>(serviceImpl.ComputeOrbitaIK));
      serviceBinder.AddMethod(__Method_GetQuaternionTransform, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Reachy.Sdk.Kinematics.LookVector, global::Reachy.Sdk.Kinematics.Quaternion>(serviceImpl.GetQuaternionTransform));
    }

  }
}
#endregion
